# Generated by Django 2.2.4 on 2021-06-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntranceAccessRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('entrance_punch_code', models.CharField(max_length=40, verbose_name='门禁刷卡编码')),
                ('device_code', models.CharField(max_length=200, verbose_name='门禁设备编码')),
                ('device_name', models.CharField(max_length=60, verbose_name='门禁设备名称')),
                ('record_time', models.DateTimeField(verbose_name='门禁刷卡时间')),
                ('card_no', models.CharField(max_length=30, verbose_name='卡号')),
                ('holder', models.CharField(max_length=32, verbose_name='持卡人姓名')),
                ('department', models.CharField(blank=True, max_length=64, verbose_name='部门名称')),
                ('jobs', models.CharField(blank=True, max_length=64, verbose_name='岗位')),
                ('code_name', models.CharField(blank=True, max_length=64, verbose_name='门禁代号')),
                ('in_out', models.SmallIntegerField(choices=[(0, '进'), (1, '出')], verbose_name='进出方向')),
                ('region_id', models.CharField(max_length=10, verbose_name='刷卡区域id')),
            ],
            options={
                'verbose_name': '门禁通行记录',
                'verbose_name_plural': '门禁通行记录',
                'db_table': 'tb_entrance_access_records',
            },
        ),
        migrations.CreateModel(
            name='PlanInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan_name', models.CharField(max_length=20, verbose_name='预案名称')),
                ('plan_code', models.CharField(max_length=20, verbose_name='预案编码')),
                ('keywords', models.CharField(max_length=10, verbose_name='关键字')),
                ('description', models.TextField(blank=True, verbose_name='预案说明')),
                ('gis_basic_info', models.TextField(verbose_name='gis基础信息')),
                ('gis_field', models.TextField(verbose_name='gis点位信息')),
                ('doc_file', models.FileField(upload_to='plan_file', verbose_name='文件地址')),
            ],
            options={
                'verbose_name': '预案信息',
                'verbose_name_plural': '预案信息',
                'db_table': 'tb_plan_info',
            },
        ),
        migrations.CreateModel(
            name='WatchAddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('department_name', models.CharField(max_length=20, verbose_name='部门名称')),
                ('staff_name', models.CharField(max_length=10, verbose_name='值班人员')),
                ('contact_mobile', models.CharField(max_length=20, verbose_name='联系电话')),
                ('duty_date', models.DateField(verbose_name='值班日期')),
            ],
            options={
                'verbose_name': '值班通讯录',
                'verbose_name_plural': '值班通讯录',
                'db_table': 'tb_watch_address_book',
            },
        ),
        migrations.CreateModel(
            name='StaffInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('staff_name', models.CharField(max_length=10, verbose_name='员工姓名')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('other', '其它')], default='male', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('phone_number', models.CharField(max_length=20, verbose_name='联系电话')),
                ('entry_date', models.DateField(verbose_name='入职日期')),
                ('picture', models.TextField(blank=True, verbose_name='照片')),
                ('gis_basic_info', models.TextField(blank=True, verbose_name='gis基础信息')),
                ('gis_field', models.CharField(blank=True, max_length=100, verbose_name='gis点位信息(x,y)')),
                ('description', models.TextField(blank=True, verbose_name='备注')),
                ('pass_card_number', models.CharField(blank=True, max_length=35, verbose_name='通行证卡号')),
                ('work_number', models.CharField(blank=True, max_length=55, null=True, unique=True, verbose_name='工号')),
                ('identity_card', models.CharField(blank=True, max_length=30, verbose_name='身份证')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='住址')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='国籍')),
                ('nation', models.CharField(blank=True, max_length=10, verbose_name='民族')),
                ('jobs', models.CharField(blank=True, max_length=20, verbose_name='岗位')),
                ('department_name', models.CharField(blank=True, max_length=20, verbose_name='部门名称')),
                ('son_department_name', models.CharField(blank=True, max_length=20, verbose_name='子部门名称')),
                ('pass_area', models.TextField(blank=True, verbose_name='通行区域')),
                ('entrances_area', models.TextField(blank=True, verbose_name='门禁区域')),
                ('pass_card_type', models.CharField(blank=True, choices=[('L', '长期'), ('S', '短期'), ('T', '临时'), ('G', '警卫'), ('E', '应急')], max_length=1, verbose_name='卡证类型')),
                ('card_create_time', models.DateField(blank=True, null=True, verbose_name='制证日期')),
                ('card_handle_time', models.DateField(blank=True, null=True, verbose_name='办证日期')),
                ('card_expire_time', models.DateField(blank=True, null=True, verbose_name='超期日期')),
                ('is_black', models.BooleanField(blank=True, null=True, verbose_name='是否黑名单')),
                ('is_lock', models.BooleanField(blank=True, null=True, verbose_name='是否锁定')),
                ('black_reason', models.CharField(blank=True, max_length=100, verbose_name='黑名单原因')),
                ('lock_reason', models.CharField(blank=True, max_length=100, verbose_name='锁定原因')),
                ('card_status', models.SmallIntegerField(blank=True, choices=[(1, '正常'), (2, '申请'), (3, '变更'), (4, '挂失'), (5, '补办'), (6, '已挂失'), (7, '已回收'), (8, '待申请'), (9, '到期'), (10, '注销')], null=True, verbose_name='卡证状态')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='当前积分')),
                ('pass_card_max_count', models.IntegerField(blank=True, null=True, verbose_name='最大允许通行次数')),
                ('pass_card_current_count', models.IntegerField(blank=True, null=True, verbose_name='已通行次数')),
                ('staff_type', models.CharField(choices=[('ab', '安保'), ('aj', '安检'), ('xf', '消防'), ('other', '其它')], default='ab', max_length=10, verbose_name='类型')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Department', verbose_name='所属部门')),
            ],
            options={
                'verbose_name': '员工信息',
                'verbose_name_plural': '员工信息',
                'db_table': 'tb_staff_info',
            },
        ),
    ]
