# Generated by Django 2.2.4 on 2021-06-25 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbacklog',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userbacklog',
            name='backlog_type',
            field=models.CharField(choices=[('DS', '设备工单'), ('ES', '事件工单')], max_length=20, verbose_name='待办事件类型'),
        ),
    ]
