# Generated by Django 2.2.4 on 2021-06-28 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210625_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbacklog',
            name='user',
        ),
    ]
