# Generated by Django 2.2.4 on 2021-06-01 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0001_initial'),
        ('situations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('event_name', models.CharField(max_length=50, verbose_name='事件名称')),
                ('event_type', models.SmallIntegerField(choices=[(1, '自动上报'), (2, '人工上报'), (3, '预警')], default=1, verbose_name='事件类型')),
                ('event_code', models.CharField(max_length=50, unique=True, verbose_name='事件编号')),
                ('alarm_time', models.DateTimeField(verbose_name='报警时间')),
                ('area_code', models.CharField(blank=True, max_length=20, verbose_name='所属区域')),
                ('floor_code', models.CharField(blank=True, max_length=20, verbose_name='所属楼层')),
                ('priority', models.SmallIntegerField(db_index=True, default=4, verbose_name='事件等级（1-4，1级为最高级别）')),
                ('event_state', models.CharField(max_length=20, verbose_name='状态')),
                ('location_detail', models.CharField(blank=True, max_length=30, verbose_name='事件位置(x,y)')),
                ('event_description', models.TextField(blank=True, verbose_name='事件描述')),
            ],
            options={
                'verbose_name': '基础报警事件',
                'verbose_name_plural': '基础报警事件',
                'db_table': 'tb_basic_alarm_event',
                'index_together': {('event_type', 'event_state', 'create_time')},
            },
        ),
        migrations.CreateModel(
            name='DeviceAlarmEvent',
            fields=[
                ('alarmevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.AlarmEvent')),
                ('subsystem_event_id', models.CharField(max_length=50, unique=True, verbose_name='子系统事件ID')),
                ('alarm_type', models.CharField(blank=True, max_length=20, verbose_name='报警类型(布控、行为识别..)')),
                ('belong_system', models.CharField(max_length=20, verbose_name='所属系统')),
                ('is_misrepresent', models.BooleanField(null=True, verbose_name='是否误报')),
                ('acknowledged_user', models.CharField(blank=True, max_length=20, verbose_name='确认人')),
                ('acknowledged_time', models.DateTimeField(null=True, verbose_name='确认时间')),
                ('acknowledged_opinion', models.CharField(blank=True, max_length=255, verbose_name='确认意见')),
                ('dispose_user', models.CharField(blank=True, max_length=20, verbose_name='处置人')),
                ('dispose_time', models.DateTimeField(null=True, verbose_name='处置时间')),
                ('dispose_opinion', models.CharField(blank=True, max_length=255, verbose_name='处置意见')),
                ('audit_user', models.CharField(blank=True, max_length=20, verbose_name='审核人')),
                ('audit_time', models.DateTimeField(null=True, verbose_name='审核时间')),
                ('audit_opinion', models.CharField(blank=True, max_length=255, verbose_name='审核意见')),
                ('pass_id', models.CharField(blank=True, max_length=50, verbose_name='门禁通行证id')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceInfo', verbose_name='关联设备')),
            ],
            options={
                'verbose_name': '系统报警事件',
                'verbose_name_plural': '系统报警事件',
                'db_table': 'tb_system_alarm_event',
            },
            bases=('events.alarmevent',),
        ),
        migrations.CreateModel(
            name='PersonAlarmEvent',
            fields=[
                ('alarmevent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.AlarmEvent')),
                ('alarm_person_name', models.CharField(max_length=20, verbose_name='报警人名称')),
                ('alarm_person_type', models.SmallIntegerField(choices=[(1, '公众'), (2, '机场人员')], verbose_name='报警人类别')),
                ('alarm_person_mobile', models.CharField(blank=True, max_length=20, verbose_name='报警人电话')),
                ('handled_user', models.CharField(blank=True, max_length=20, verbose_name='处理人')),
                ('handled_time', models.DateTimeField(null=True, verbose_name='处理时间')),
                ('handled_opinion', models.CharField(blank=True, max_length=255, verbose_name='处理意见')),
                ('audit_user', models.CharField(blank=True, max_length=20, verbose_name='审核人')),
                ('audit_time', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('audit_opinion', models.CharField(blank=True, max_length=255, verbose_name='审核意见')),
                ('gis_basic_info', models.TextField(blank=True, verbose_name='gis基础信息')),
                ('gis_field', models.CharField(blank=True, max_length=100, verbose_name='gis点位信息(x,y)')),
            ],
            options={
                'verbose_name': '人工报警事件',
                'verbose_name_plural': '人工报警事件',
                'db_table': 'tb_person_alarm_event',
            },
            bases=('events.alarmevent',),
        ),
        migrations.CreateModel(
            name='PlaceSafeguardRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('safeguard_name', models.CharField(max_length=50, verbose_name='保障节点名称')),
                ('safeguard_time', models.DateTimeField(verbose_name='保障节点时间')),
                ('safeguard_image_url', models.CharField(blank=True, max_length=200, verbose_name='机位保障图片地址')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceInfo', verbose_name='摄像机设备')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='situations.FlightInfo')),
            ],
            options={
                'verbose_name': '机位保障记录',
                'verbose_name_plural': '机位保障记录',
                'db_table': 'tb_place_safeguard_record',
            },
        ),
        migrations.CreateModel(
            name='EventWorkSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('work_sheet_code', models.CharField(max_length=20, unique=True, verbose_name='工单编号')),
                ('sheet_state', models.CharField(choices=[('unaudited', '待审核'), ('closed', '已关闭')], default='unaudited', max_length=20, verbose_name='工单状态')),
                ('close_user', models.CharField(blank=True, max_length=20, verbose_name='销单人')),
                ('close_time', models.DateTimeField(blank=True, null=True, verbose_name='销单时间')),
                ('close_opinion', models.CharField(blank=True, max_length=255, verbose_name='销单备注')),
                ('alarm_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.AlarmEvent', verbose_name='事件')),
                ('dispose_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='处置人')),
            ],
            options={
                'verbose_name': '事件工单',
                'verbose_name_plural': '事件工单',
                'db_table': 'tb_event_work_sheet',
            },
        ),
        migrations.CreateModel(
            name='DeployPersonSnapRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('snap_image_url', models.CharField(max_length=200, verbose_name='抓拍图片地址')),
                ('snap_time', models.DateTimeField(verbose_name='抓拍时间')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceInfo', verbose_name='摄像机设备')),
            ],
            options={
                'verbose_name': '实时布控人员抓拍',
                'verbose_name_plural': '实时布控人员抓拍',
                'db_table': 'tb_deploy_snap_record',
            },
        ),
        migrations.CreateModel(
            name='CameraLineUpRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('detection_time', models.DateTimeField(verbose_name='检测时间')),
                ('current_queue_number', models.IntegerField(verbose_name='当前排队人数')),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceInfo', verbose_name='摄像机')),
            ],
            options={
                'verbose_name': '排队人数',
                'verbose_name_plural': '排队人数',
                'db_table': 'tb_line_up_records',
            },
        ),
        migrations.CreateModel(
            name='PostureAlarmRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alarm_image_url', models.CharField(blank=True, max_length=200, verbose_name='报警图片地址')),
                ('action_type', models.SmallIntegerField(choices=[(1, '奔跑'), (2, '打架'), (3, '倒地'), (4, '下蹲'), (5, '打电话')], verbose_name='姿态动作事件类型')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='situations.ResourceInfo', verbose_name='关联资源')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.DeviceAlarmEvent', verbose_name='关联设备报警事件')),
            ],
            options={
                'verbose_name': '姿态动作报警记录',
                'verbose_name_plural': '姿态动作报警记录',
                'db_table': 'tb_posture_alarm_record',
            },
        ),
        migrations.CreateModel(
            name='PlaceAlarmRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alarm_image_url', models.CharField(blank=True, max_length=200, verbose_name='报警图片地址')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='situations.ResourceInfo', verbose_name='关联资源')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.DeviceAlarmEvent', verbose_name='关联设备报警事件')),
            ],
            options={
                'verbose_name': '机位报警记录',
                'verbose_name_plural': '机位报警记录',
                'db_table': 'tb_place_alarm_record',
            },
        ),
        migrations.CreateModel(
            name='PersonDensityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alarm_image_url', models.CharField(blank=True, max_length=200, verbose_name='报警图片地址')),
                ('total_people_number', models.IntegerField(verbose_name='报警人数')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='situations.ResourceInfo', verbose_name='关联资源')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.DeviceAlarmEvent', verbose_name='关联设备报警事件')),
            ],
            options={
                'verbose_name': '密度报警记录',
                'verbose_name_plural': '密度报警记录',
                'db_table': 'tb_density_alarm_record',
            },
        ),
        migrations.CreateModel(
            name='PeopleCountingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('statistical_time', models.DateTimeField(verbose_name='统计时间')),
                ('total_people', models.IntegerField(default=1, verbose_name='统计总人数')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.DeviceInfo', verbose_name='摄像机设备')),
            ],
            options={
                'verbose_name': '实时人数统计记录',
                'verbose_name_plural': '实时人数统计记录',
                'db_table': 'tb_people_counting_records',
                'unique_together': {('camera', 'statistical_time')},
            },
        ),
        migrations.CreateModel(
            name='DeviceAlarmEventPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='报警图片地址')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.DeviceAlarmEvent', verbose_name='报警事件')),
            ],
            options={
                'verbose_name': '事件报警图片',
                'verbose_name_plural': '事件报警图片',
                'db_table': 'tb_event_picture',
            },
        ),
        migrations.CreateModel(
            name='DeviceAlarmEventCamera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='摄像机编码')),
                ('preset', models.CharField(blank=True, max_length=5, null=True, verbose_name='摄像机预置位')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.DeviceAlarmEvent', verbose_name='报警事件')),
            ],
            options={
                'verbose_name': '事件关联摄像机',
                'verbose_name_plural': '事件关联摄像机',
                'db_table': 'tb_event_relate_camera',
            },
        ),
        migrations.CreateModel(
            name='DeployAlarmRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alarm_image_url', models.CharField(blank=True, max_length=200, verbose_name='报警图片地址')),
                ('person_db_image_url', models.CharField(max_length=200, verbose_name='人像库图片地址')),
                ('score', models.FloatField(verbose_name='相似度')),
                ('name', models.CharField(blank=True, max_length=64, verbose_name='姓名')),
                ('sex', models.CharField(blank=True, max_length=5, verbose_name='性别')),
                ('born', models.CharField(blank=True, max_length=35, verbose_name='出生日期')),
                ('type', models.CharField(blank=True, max_length=15, verbose_name='证件类型')),
                ('number', models.CharField(blank=True, max_length=30, verbose_name='证件号')),
                ('country', models.CharField(blank=True, max_length=64, verbose_name='国家')),
                ('city', models.CharField(blank=True, max_length=64, verbose_name='城市')),
                ('db_name', models.CharField(blank=True, max_length=64, verbose_name='库名称')),
                ('monitor_type', models.CharField(blank=True, max_length=11, verbose_name='布控类型')),
                ('db_type', models.CharField(blank=True, max_length=20, verbose_name='库类型')),
                ('level', models.CharField(blank=True, max_length=6, verbose_name='库等级')),
                ('customType', models.BooleanField(verbose_name='自定义库类型')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='situations.ResourceInfo', verbose_name='关联资源')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.DeviceAlarmEvent', verbose_name='关联设备报警事件')),
            ],
            options={
                'verbose_name': '实时布控人员报警记录',
                'verbose_name_plural': '实时布控人员报警记录',
                'db_table': 'tb_deploy_alarm_record',
            },
        ),
        migrations.CreateModel(
            name='BehaviorAlarmRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('alarm_image_url', models.CharField(blank=True, max_length=200, verbose_name='报警图片地址')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='situations.ResourceInfo', verbose_name='关联资源')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.DeviceAlarmEvent', verbose_name='关联设备报警事件')),
            ],
            options={
                'verbose_name': '行为识别报警记录',
                'verbose_name_plural': '行为识别报警记录',
                'db_table': 'tb_behavior_alarm_record',
            },
        ),
    ]
