# Generated by Django 2.2.4 on 2021-06-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='alarmevent',
            index_together={('event_type', 'priority', 'event_state', 'create_time')},
        ),
    ]
