# Generated by Django 2.2.4 on 2021-06-01 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GisMap',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('map_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='地图id')),
                ('map_class', models.CharField(max_length=100, verbose_name='大区域')),
                ('map_name', models.CharField(max_length=100, verbose_name='小区域')),
                ('map_type', models.CharField(max_length=100, verbose_name='设备类型')),
            ],
            options={
                'verbose_name': 'gis地图',
                'verbose_name_plural': 'gis地图',
                'db_table': 'tb_gis_map',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_key', models.CharField(choices=[('security_speed', '安检速度(单位:人/小时)'), ('event_close', '报警事件自动关闭(单位:小时)'), ('event_delete', '报警事件删除(单位:天)'), ('analysis_alarm_delete', '视频分析报警(单位:天)'), ('subsystem_current_delete', '子系统实时消息(单位:天)'), ('analysis_current_delete', '视频分析实时消息(单位:天)')], max_length=50, unique=True, verbose_name='系统配置名称')),
                ('config_value', models.CharField(max_length=100, verbose_name='系统配置值')),
                ('is_exposed', models.BooleanField(default=True, verbose_name='是否暴露给用户')),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
                'db_table': 'tb_system_config',
            },
        ),
        migrations.CreateModel(
            name='GisLayer',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('layer_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='图层id')),
                ('layer_name', models.CharField(max_length=100, verbose_name='图层名称')),
                ('layer_type', models.CharField(max_length=100, verbose_name='图层类型')),
                ('resource_name', models.CharField(max_length=200, verbose_name='资源信息')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configurations.GisMap', verbose_name='关联地图')),
            ],
            options={
                'verbose_name': 'gis图层',
                'verbose_name_plural': 'gis图层',
                'db_table': 'tb_gis_layer',
            },
        ),
    ]
