# Generated by Django 2.2.4 on 2021-06-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GisPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('system_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='cad名称')),
                ('object_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='cadID')),
                ('dev_guid', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='设备id')),
                ('map_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='gis地图id')),
                ('layer_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='gis图层id')),
                ('floor_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='楼层')),
                ('dev_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备名')),
                ('cad_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='cad图纸工程编码')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('dev_type', models.CharField(blank=True, max_length=200, null=True, verbose_name='设备类型')),
                ('dev_manu', models.CharField(blank=True, max_length=200, null=True, verbose_name='厂商')),
                ('camera_ip', models.CharField(blank=True, max_length=200, null=True, verbose_name='相机ip')),
                ('x', models.CharField(blank=True, max_length=200, null=True, verbose_name='x点位')),
                ('y', models.CharField(blank=True, max_length=200, null=True, verbose_name='y点位')),
                ('date_time', models.CharField(blank=True, max_length=200, null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': 'gis点位信息',
                'verbose_name_plural': 'gis点位信息',
                'db_table': 'tb_gis_point',
            },
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='config_key',
            field=models.CharField(choices=[('event_close_1', '1级报警事件自动关闭(单位:小时)'), ('event_close_2', '2级报警事件自动关闭(单位:小时)'), ('event_close_3', '3级报警事件自动关闭(单位:小时)'), ('event_close_4', '4级报警事件自动关闭(单位:小时)'), ('security_speed', '安检速度(单位:人/小时)'), ('event_delete', '报警事件删除(单位:天)'), ('analysis_alarm_delete', '视频分析报警删除(单位:天)'), ('subsystem_current_delete', '子系统实时消息删除(单位:天)'), ('analysis_current_delete', '视频分析实时消息删除(单位:天)')], max_length=50, unique=True, verbose_name='系统配置名称'),
        ),
    ]
